# Generated by Django 2.2.16 on 2022-01-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220104_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
