# Generated by Django 2.2.16 on 2022-01-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220110_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='type',
            new_name='ingredient_type',
        ),
    ]
