# Generated by Django 2.2.16 on 2022-01-31 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True,
                                  serialize=False, verbose_name='ID')),
                ('recipe',
                 models.ForeignKey(
                         on_delete=django.db.models.deletion.CASCADE,
                         related_name='cart', to='recipes.Recipe',
                         verbose_name='Рецепт'
                         )),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='cart',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Пользователь')),
            ],
        ),
    ]
