# Generated by Django 2.2.16 on 2022-02-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220205_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={
                'ordering': ['user__username'],
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows'},
        ),
    ]
